[workspace]
authors = ["Dan Zimmerman <code@danzimmerman.com>"]
channels = ["conda-forge", "robostack-jazzy"]
name = "ros_jazzy_core_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
