[workspace]
authors = ["Dan Zimmerman <code@danzimmerman.com>"]
channels = ["conda-forge", "robostack-jazzy"]
name = "ros_jazzy_core_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[activation.env]
RMW_IMPLEMENTATION = "rmw_zenoh_cpp"

[dependencies]
ros-jazzy-ros-core = ">=0.11.0,<0.12"
ros-jazzy-rmw-zenoh-cpp = ">=0.2.9,<0.3"
ros-jazzy-demo-nodes-cpp = ">=0.33.9,<0.34"
