[workspace]
authors = ["Dan Zimmerman <code@danzimmerman.com>"]
channels = ["conda-forge"]
name = "bare_zenoh_interop_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.14.*"
rosbags = ">=0.11.0,<0.12"
zenoh = ">=1.7.2,<2"
